title: React Native
email: kartikssj@gmail.com
description: >-
  Documentation for RN platform libraries
baseurl: "/rn" 
url: "https://kartikssj.github.io"
theme: just-the-docs
plugins:
  - jekyll-feed

